services:
  otelcol:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol
    ports:
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel-collector-config.yaml:/otelcol/config.yaml

  app_collector_local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_collector_local
    environment:
      - IP_ADDR=${IP_ADDR}
    restart: unless-stopped