services:
  app_collector_local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_collector_local
    environment:
      - IP_ADDR=${IP_ADDR}
      - hostname=${hostname}
    restart: unless-stopped