services:
  app_collector_local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_collector_local
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src/alerts.json:/app/src/alerts.json